"use client";

import { useState } from "react";
import Alert from "@mui/material/Alert";
import Box from "@mui/material/Box";
import Button from "@mui/material/Button";
import Dialog from "@mui/material/Dialog";
import DialogActions from "@mui/material/DialogActions";
import DialogContent from "@mui/material/DialogContent";
import DialogTitle from "@mui/material/DialogTitle";
import Stack from "@mui/material/Stack";
import Step from "@mui/material/Step";
import StepLabel from "@mui/material/StepLabel";
import Stepper from "@mui/material/Stepper";
import TextField from "@mui/material/TextField";
import Typography from "@mui/material/Typography";
import ArrowBackIcon from "@mui/icons-material/ArrowBack";
import ArrowForwardIcon from "@mui/icons-material/ArrowForward";
import PersonAddOutlinedIcon from "@mui/icons-material/PersonAddOutlined";
import { mutate } from "swr";
import { createOrganisationUser } from "@/lib/api/api";

const STEPS = ["Identity", "Contact"];

type Props = {
  open: boolean;
  onClose: () => void;
  orgId: string;
  onCreated?: () => void;
};

export default function AddPersonWizard({ open, onClose, orgId, onCreated }: Props) {
  const [step, setStep] = useState(0);
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  function reset() {
    setStep(0);
    setName("");
    setEmail("");
    setError(null);
  }

  function handleClose() {
    reset();
    onClose();
  }

  async function handleSubmit() {
    setLoading(true);
    setError(null);
    try {
      await createOrganisationUser(orgId, { name: name.trim(), email: email.trim() });
      await mutate(["organisation-users", orgId]);
      onCreated?.();
      handleClose();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to create person");
    } finally {
      setLoading(false);
    }
  }

  return (
    <Dialog open={open} onClose={handleClose} maxWidth="sm" fullWidth>
      <DialogTitle sx={{ pb: 1 }}>
        <Box sx={{ display: "flex", alignItems: "center", gap: 1.5 }}>
          <Box
            sx={{
              width: 40,
              height: 40,
              borderRadius: "50%",
              bgcolor: "primary.main",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
            }}
          >
            <PersonAddOutlinedIcon sx={{ color: "#fff" }} />
          </Box>
          <Box>
            <Typography variant="h6">Add Person</Typography>
            <Typography variant="body2" color="text.secondary">
              Register a new team member or technician.
            </Typography>
          </Box>
        </Box>
      </DialogTitle>

      <DialogContent>
        <Stepper activeStep={step} alternativeLabel sx={{ mb: 3 }}>
          {STEPS.map((label) => (
            <Step key={label}>
              <StepLabel>{label}</StepLabel>
            </Step>
          ))}
        </Stepper>

        {error ? <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert> : null}

        {step === 0 ? (
          <Stack spacing={2}>
            <Typography variant="subtitle2" color="text.secondary">
              Personal details
            </Typography>
            <TextField
              required
              label="Full name"
              placeholder="e.g. James Smith"
              value={name}
              onChange={(e) => setName(e.target.value)}
              fullWidth
            />
            <TextField
              label="Employee reference"
              value="Assigned on save"
              disabled
              helperText="User ID is generated by the system when the account is created."
              fullWidth
            />
          </Stack>
        ) : null}

        {step === 1 ? (
          <Stack spacing={2}>
            <Typography variant="subtitle2" color="text.secondary">
              Contact information
            </Typography>
            <TextField
              required
              type="email"
              label="Email"
              placeholder="e.g. james.smith@company.com"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              fullWidth
            />
          </Stack>
        ) : null}
      </DialogContent>

      <DialogActions sx={{ px: 3, pb: 2, justifyContent: "space-between" }}>
        <Button onClick={handleClose} disabled={loading}>
          Cancel
        </Button>
        <Box sx={{ display: "flex", gap: 1 }}>
          {step > 0 ? (
            <Button
              startIcon={<ArrowBackIcon />}
              onClick={() => setStep((s) => s - 1)}
              disabled={loading}
            >
              Back
            </Button>
          ) : null}
          {step < STEPS.length - 1 ? (
            <Button
              variant="contained"
              endIcon={<ArrowForwardIcon />}
              onClick={() => setStep((s) => s + 1)}
              disabled={!name.trim()}
            >
              Next
            </Button>
          ) : (
            <Button
              variant="contained"
              onClick={handleSubmit}
              disabled={loading || !name.trim() || !email.trim()}
            >
              {loading ? "Creating…" : "Create person"}
            </Button>
          )}
        </Box>
      </DialogActions>
    </Dialog>
  );
}
